### ISSUE TITLE
Is this repo being maintained?

### ISSUE THREAD

**Issue by prattcmp** [dgilland/flask-pushjack#4]
It looks like pushjack is multiple versions ahead of flask-pushjack. Is this version being maintained?

**Comment by dgilland** [comment]
This library is mostly just glue code so that pushjack is better integrated within the flask ecosystem. It requires pushjack to be >= 1.0.0 (minmum compatible version) but should work with 1.4.0 (latest as of this writing). I don’t make a new release of this library unless there’s a breaking change in pushjack that needs to be addressed here too. 

Have you encountered an issue with using the latest pushjack version with this library?

**Comment by prattcmp** [comment]
Everything seems to be working fine. Just wanted to make sure it was being maintained as we'll be relying on it in the future.
